---
resources:
- name: repo-master
  type: git
  source:
    uri: https://github.com/malston/ardo-boshrelease.git

- name: "dev-release"
  type: s3
  source:
    bucket: {{release-bucket}}
    regexp: "ardo-(.*).tgz"
    access_key_id: {{release-access-key}}
    secret_access_key: {{release-secret-key}}

- name: "tile-dev-release"
  type: s3
  source:
    bucket: {{release-bucket}}
    regexp: "p-ardo-(.*).pivotal"
    access_key_id: {{release-access-key}}
    secret_access_key: {{release-secret-key}}

jobs:
- name: create-release
  public: true
  plan:
  - get: repo
    resource: "repo-master"
  - task: create-release
    file: repo/ci/scripts/create-release/task.yml
  - put: dev-release
    params:
      from: "create-release/repo/dev_releases/ardo/ardo-(.+).tgz"
#      to: "dev_releases/"

- name: create-piv-tile
  public: true
  plan:
  - get: "repo"
    resource: "repo-master"
  - get: "release"
    resource: "dev-release"
#    params:
#      from: "dev_releases/ardo-(.+).tgz"
  - task: create-tile
    file: repo/ci/scripts/create-tile/task.yml
  - put: tile-dev-release
    params:
      from: "p-ardo-(.+).pivotal"
#      to: "dev_releases/"
