release-access-key: AKIAJLZX6E4PDXQPBKHA
release-secret-key: 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

#test-director-target: "https://192.168.50.4:25555"
#test-director-username: "admin"
#test-director-password: "admin"
