---
name: ardo
director_uuid: c6f166bd-ddac-4f7d-9c57-d11c6ad5133b

releases:
- name: ardo
  version: latest

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  serial: false #Deploy jobs in parallel
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 1
  max_errors: 1

resource_pools:
- name: warden
  network: default
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}

jobs:
- name: ardo_web
  release: ardo
  templates:
  - name: ardo_dns
  - name: web_ui
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.2
  properties:
    web_ui:
      port: 8000
    ardo_dns:
      ip: 8.8.8.8

# Warden CPI requires crappy network settings; so "hide" them away here
networks:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static: []

apply_spec:
  properties:
    ntp:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
      - 3.pool.ntp.org
